export const FETCH_TOKEN = "FETCH_TOKEN";
export const SET_TOKEN = "SET_TOKEN";
export const GET_TOKEN = "GET_TOKEN";

export const SET_USER = "SET_USER";

export const FETCH_POSTS = "FETCH_POSTS";
export const POST_LOADING = "POST_LOADING";
export const POST_REFRESHING = "POST_REFRESHING";
export const LIKE_POST = "LIKE_POST";
export const SELECT_POST = "SELECT_POST";

export const FETCH_SELECTED_POST = "FETCH_SELECTED_POST";
export const SELECTED_POST_LOADING = "SELECTED_POST_LOADING";
export const SELECTED_POST_REFRESHING = "SELECTED_POST_REFRESHING";

export const FETCH_PROFILE = "FETCH_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
